### PR TITLE
Fix base fee encoding in payload header response

### PR DESCRIPTION
**Pull request by g11tech**
Fix encoding in payload header as well

### CODE REVIEW

**Comment by metachris** [comment]
This PR should go to https://github.com/protolambda/mergemock

**Comment by g11tech** [comment]
> This PR should go to https://github.com/protolambda/mergemock

i think this PR on merge will update the adjust base fee encoding PR as well as i opened the merge on the branch used to open PR. in case you still want I can point it over there

**Comment by metachris** [comment]
Isn't that the same as https://github.com/protolambda/mergemock/pull/52

**Comment by metachris** [comment]
Closing this, we're going to delete this repository altogether since it's not needed anymore

**Pull request closed without merging**
